# NumPy (Numerical Python)

- NumPy is a Python library used for working with arrays.
- NumPy has multiple functions for working in domain of linear algebra, fourier transform, and matrices.

### What is an Array?
  - Array is "Homogenious". i.e all the values in an array must of of the same type.

  One-dimentional Array
  - One-dimentional array is somewhat similar to List in the sense that it is ordered, mutatable and enclosed on square brackets.

    ```
      1-Dimentional Array
      
      [12,45,66,21,10,20]
    
    ```
  Two-dimentional array
  - Two-dimentional arrays are list of lists. Also can be refered to as Matrix.
  - Matrices are arranged in ROWS and COLUMNS.
  - Have two axes:
    - 0-axes (rows)
    - 1-axes (cols)
    
    
    ```
      2-Dimentional Array
      
      [22,33,44,55,66,77]
      [23,74,66,35,78,99]
      [10,29,39,47,22,12]
    ```

  - Note: In NumPy, the numbering starts with zero.

### Install NumPy Library

In [72]:
# Install using pip package manager

# pip install pandas

In [ ]:
# Install using conda package manager

# conda install pandas

### Import NumPy library

In [74]:
import numpy as np

### Creating an Array

In [75]:
# You can use python list, or tuple or set to create an Array

num_list = [10,20,30,40,50]
num_tuple = (10,20,30,40,50)
num_set = {10,20,30,40,50}

In [83]:
np.array(num_list)

array([10, 20, 30, 40, 50])

In [84]:
np.array(num_tuple)

array([10, 20, 30, 40, 50])

In [85]:
np.array(num_set)

array({50, 20, 40, 10, 30}, dtype=object)

In [86]:
type(np.array(num_list))

numpy.ndarray

### Check the shape of the Matrix

In [87]:
np.shape(num_list)

(5,)

2-Dimentional Array

In [90]:
array_2d_list = ([10, 20, 30, 40, 50],[10, 20, 30, 40, 50],[10, 20, 30, 40, 50])

In [92]:
np.shape(array_2d_list)

(3, 5)

### [NumPy Datatype Objects](https://numpy.org/doc/stable/user/basics.types.html)

In [96]:
# Short Integer

np.short(num_list)

array([10, 20, 30, 40, 50], dtype=int16)

In [99]:
# Float

np.array(num_list,dtype='e')

array([10., 20., 30., 40., 50.], dtype=float16)

In [103]:
# Longdouble

np.array(num_list,dtype='g')

array([10., 20., 30., 40., 50.], dtype=float64)

In [106]:
# Boolean

temp_numlist = [10,'',30]
np.array(temp_numlist,dtype='?')

array([ True, False,  True])